services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'docker'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: "3306"
      PMA_ARBITRARY: 1
    ports:
      - '8081:80'
  